// client stub is JS (CommonJS) generated by grpc-web -> namespace import with .js
import * as PingClient from "../grpc/ping_grpc_web_pb.js";

export const grpcClient = new PingClient.PingServiceClient(
    "http://localhost:8080",
    null,
    {}
);